#!/usr/bin/env python3

# 			 --------------------------------------------------
#				  GarudaTools-V1.10
# 			 --------------------------------------------------
#		 Copyright (C) 2017 M4st3r L1nux Indonesia (Jh0n 1sl4nskh4_404)

# 	Izin diberikan secara cuma-cuma kepada siapa saja yang memperoleh
# salinan perangkat lunak ini dan file dokumentasi yang terkait (a 
# "Software"), untuk menangani Perangkat Lunak tanpa batasan, termasuk
# tanpa batasan hak untuk menggunakan, menyalin, memodifikasi, menggabungkan, menerbitkan,
# mendistribusikan, mensublisensikan, dan / atau menjual salinan Perangkat Lunak, dan ke
# Izinkan orang untuk siapa Perangkat Lunak dilengkapi untuk melakukannya, tunduk pada # kondisi berikut:

#		Pemberitahuan hak cipta di atas dan pemberitahuan izin ini harus disertakan # di semua salinan atau sebagian besar Perangkat Lunak.

#		PERANGKAT LUNAK INI DISEDIAKAN "APA ADANYA", TANPA JAMINAN APAPUN,
# SECARA TERSURAT MAUPUN TERSIRAT, TERMASUK NAMUN TIDAK TERBATAS PADA JAMINAN
# KELAYAKAN UNTUK DIPERDAGANGKAN, KESESUAIAN UNTUK TUJUAN TERTENTU DAN NONINFRINGEMENT.
# DALAM HAL APAPUN, PENULIS ATAU PEMEGANG HAK CIPTA TIDAK BERTANGGUNG JAWAB ATAS SETIAP
# KLAIM, KERUSAKAN ATAU KEWAJIBAN LAINNYA, BAIK DALAM TINDAKAN KONTRAK,
# TORT ATAU LAINNYA, YANG TIMBUL DARI, DARI ATAU BERHUBUNGAN DENGAN
# PERANGKAT LUNAK ATAU PENGGUNAAN ATAU DEALINGS LAIN DALAM PERANGKAT LUNAK INI.

try:

	# Import python modules
	import traceback
	import sys
	import logging
	import getopt
	import csv

	# Check python version
	req_version = (3,5)
	cur_version = sys.version_info
	if cur_version < req_version:
		print('python3.5 or greater is recommended')

	# Disable scapy warning
	logging.getLogger("scapy.runtime").setLevel(logging.ERROR)

	# Import getpath for lib path
	from core import getpath

	# Append lib path
	sys.path.append(getpath.lib())

	# Import core modules
	from core import colors
	from core import header
	from core import hftest
	from core import shell
	from core import scriptio
	from core import getpath

	# Print header
	print(header.GarudaTools)
	header.print_info()

except KeyboardInterrupt:
	sys.exit(0)

# Exception handling

def fatalerror():
	print(colors.red+"unexpected error:")
	traceback.print_exc()
	print(colors.end)
	forcetokr = input('Do you want to force to keep GarudaTools running? ')
	if forcetokr == 'yes':
		main(0, None)
	elif forcetokr == 'y':
		main(0, None)

# Start up shell

try:
	def main(scripting, scf):
		try:
			if scripting == 1:
				scriptio.run(scf)

			else:
				shell.run()

		except SystemExit as e:
			sys.exit(e)

		except:
			fatalerror()

	if __name__ == '__main__':
		scripting = 0
		scf = ""

		try:
			opts, args = getopt.getopt(sys.argv[1:], 's:t:')
			for opt, arg in opts:
				if opt in ('-t'):
					if arg == 'challenge':
						hftest.challenge()
					else:
						print(colors.red+'invalid arguments'+colors.end)

				if opt in ('-s'):
					try:
						scriptfile = open(getpath.scripts()+arg+'.hfs', 'r')
						reader = csv.reader(scriptfile)
						scf = [row for row in reader]
						scripting = 1
						print(colors.green+"entering scripting mode..."+colors.end)
					except FileNotFoundError:
						print(colors.red+'error: script not found'+colors.end)
		except getopt.GetoptError:
			print(colors.red+'invalid arguments'+colors.end)
		main(scripting, scf)

# Exceptions

except KeyboardInterrupt:
	print()

except SystemExit as e:
	print(colors.bold+"Thank you for using GarudaTools!"+colors.end)
	sys.exit(e)

except:
	fatalerror()

